---
title: "Estimators"
format:
  revealjs:
    incremental: true 
    chalkboard:
      src: chalkboard.json
      theme: whiteboard
      chalk-width: 4
editor: visual
---

## Learning Outcomes

-   Estimators

-   Unbiased Estimators

-   Bias

-   Mean Square Error

## Estimators

An *estimator* is an operation computing the value of an estimate, that targets the parameter, using measurements from a sample.

## Unbiased Estimator

An unbiased estimator $\hat\theta$ is an estimator that satisfies the following condition:

$$
E(\hat\theta) = \theta
$$

## Bias

The bias of an estimator is defined as

$$
B(\hat\theta) = E(\hat\theta)-\theta
$$

## Mean Square Error

The mean square of an estimator is $\hat\theta$ is given as

$$
\begin{eqnarray}
MSE(\hat\theta) & = & E\{(\hat\theta-\theta)^2\} \\
& = & Var(\hat\theta) + B(\hat\theta)^2
\end{eqnarray}
$$

## Is $\bar X$ an unbiased estimator of $\mu$?

Let $X_1,\ldots,X_n\overset{iid}{\sim}N(\mu,\sigma^2)$, find the bias of $\bar X$.

## Why is $S²$ divided by $n-1$ instead of $n$?

Let $X_1,\ldots,X_n\overset{iid}{\sim}N(\mu,\sigma^2)$, find the bias of $S²$.

## Problem

Let $X_1,X_2,X_3$ follow and exponential distribution with mean and variance $\lambda$ and $\lambda²$, respectively. Using the following estimators:

-   $\hat\theta_1 = X_1$

-   $\hat\theta_2 = \frac{X_1+X_2}{2}$

-   $\hat\theta_3 = \frac{X_1+2X_2}{3}$

-   $\hat\theta_4 = \frac{X_1+X_2+X_3}{3}$

Identify which estimator

1.  Is unbiased?
2.  Has the lowest variance?
