---
title: "Central Limit Theorem and other Sampling Distributions"
format:
  revealjs:
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    incremental: true 
    chalkboard:
      src: chalkboard.json
      theme: whiteboard
      chalk-width: 4
editor: visual
---

## Learning Outcomes

-   Central Limit Theorem

-   Normal Approximation of Binomial Distribution

-   Other Sampling Distributions

## Central Limit Theorem

Let $X_1, X_2, \ldots, X_n$ be identical and independent distributed random variables with $E(X_i)=\mu$ and $Var(X_i) = \sigma²$. We define

$$
Y_n = \sqrt n \left(\frac{\bar X-\mu}{\sigma}\right) \mathrm{ where }\ \bar X = \frac{1}{n}\sum^n_{i=1}X_i.
$$

Then, the distribution of the function $Y_n$ converges to a standard normal distribution function as $n\rightarrow \infty$.

## Normal Approximation of Binomial Distribution

Suppose $X\sim Bin(n,p)$, furthermore, let $\bar X = X/n$. If $n$ is large enough, then

$$
\bar X \overset{\circ}{\sim}N\left\{p,p(1-p)/n\right\}$$$$
$$

## Other Sampling Distributions

-   $\chi^2$-distribution

-   t-distribution

-   F-distribution

## $\chi^2$-distribution

Let $Z_1, Z_2,\ldots,Z_n \overset{iid}{\sim}N(0,1)$,

$$
\sum_{i=1}^nZ_i^2\sim\chi^2_n.
$$

## Independence of $\bar X$ and $S^2$

$X_1, X_2,\ldots,X_n$ form a random sample from a normal distribution, then $\bar X$ and $S^2$ are independent of each other.

## Distribution of $S^2$

Let $X_1, X_2,\ldots,X_n \overset{iid}{\sim}N(\mu,\sigma^2)$, $S^2 = \frac{1}{n-1}\sum^n_{i=1}(X_i-\bar X)^2$, and $\bar X \perp S^2$; therefore:

$$
\frac{(n-1)S^2}{\sigma^2} \sim \chi^2_{n-1}.
$$

## t-distribution

Let $Z\sim N(0,1)$, $W\sim \chi^2_\nu$, $Z\perp W$; therefore:

$$
T=\frac{Z}{\sqrt{W/\nu}} \sim t_\nu
$$

## F-distribution

Let $W_1\sim\chi^2_{\nu_1}$ $W_2\sim\chi^2_{\nu_2}$, and $W_1\perp W_2$; therefore:

$$
F = \frac{W_1/\nu_1}{W_2/\nu_2}\sim F_{\nu_1,\nu_2}
$$

### 
